name: Deploy to itch.io

on:
  workflow_dispatch:

jobs:
  deploy-itchio:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest export artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: export-web.yml
          name: web-export
          path: web/

      - name: Install butler
        run: |
          curl -L -o butler.zip https://github.com/itchio/butler/releases/latest/download/butler-linux-amd64.zip
          unzip butler.zip
          chmod +x butler

      - name: Deploy to itch.io
        run: ./butler push web/ abroederdorf/carters-games:html5
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
